theme: jekyll-theme-time-machine


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to the my application </title>
    
    <!-- update the version number as needed -->
    <script defer src="/__/firebase/9.9.1/firebase-app-compat.js"></script>
    <!-- include only the Firebase features as you need -->
    <script defer src="/__/firebase/9.9.1/firebase-auth-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-database-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-firestore-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-functions-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-messaging-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-storage-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-analytics-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-remote-config-compat.js"></script>
    <script defer src="/__/firebase/9.9.1/firebase-performance-compat.js"></script>
    <!-- 
      initialize the SDK after all desired features are loaded, set useEmulator to false
      to avoid connecting the SDK to running emulators.
    -->
    <script defer src="/__/firebase/init.js?useEmulator=true"></script>

    <style media="screen">
      body { background: #000000; color: rgba(215, 22, 141, 0.722); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
      #message { background: rgba(215, 222, 222, 0.868); max-width: 460px; margin: 100px auto 16px; padding: 40px 28px; border-radius: 30px; }
      #message h2 { color: #ff2f00; font-weight: bold; font-size: 16px; margin: 0 0 8px; }
      #message h1 { font-size: 22px; font-weight: 300; color: rgba(0, 0, 0, 0.6); margin: 0 0 16px;}
      #message p {color: #000000; line-height: 140%; margin: 10px 0 20px; font-size: 16px; }
      #message h3 {color: #000000; line-height: 140%; margin: 10px 0 20px; font-size: 16px; }

      #message a { display: block; text-align: center; background: #e81372; text-transform: uppercase; text-decoration: none; color: white; padding: 10px; border-radius: 20px; }
      #message, #message a { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }
      #load { color: rgba(0,0,0,0.4); text-align: center; font-size: 13px; }
      @media (max-width: 600px) {
        body, #message { margin-top: 0; background: white; box-shadow: none; }
        body { border-top: 16px solid #ffa100; }
      }
    </style>
  </head>
  <body>
    <div id="message">
      <h2 style="text-align: center;"> 😍WELCOME </h2>
      <h1>This project was made for practice purpose</h1>
     
      <p>Please do visit my instagram for more info... </p>
      <h3 style="text-align: center;">💢💢💢💢💢 </h3>
      <a target="_blank" href="https://www.instagram.com/_rohitnadimetla_/">click here to visit instagram profile ✔✔✔</a>
    </div>


    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const loadEl = document.querySelector('#load');
   </script>
  </body>
</html>
